services:
  seek:
    image: crs4/lifemonitor-tests:seek-1.16
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    volumes:
      - ./certs/lm.crt:/certs/lm.crt:ro
      - ./certs/lm.key:/certs/lm.key:ro
      - ./tests/config/registries/seek/nginx.conf:/seek/nginx.conf:ro
      - ./tests/config/registries/seek/doorkeeper.rb:/seek/config/initializers/doorkeeper.rb
    networks:
      - life_monitor

  jenkins:
    image: crs4/lifemonitor-tests:jenkins
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - life_monitor

networks:
  life_monitor:
    name: life_monitor
